Minsal\CoreBundle\Entity\CatEstablecimiento:
    type: entity
    table: cat_establecimiento
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        idTipoEstablecimiento:
            type: integer
            nullable: true
            unsigned: false
            column: id_tipo_establecimiento
        nombre:
            type: string
            nullable: true
            length: 150
            fixed: false
        direccion:
            type: string
            nullable: true
            length: 300
            fixed: false
        telefono:
            type: string
            nullable: true
            length: 15
            fixed: false
        fax:
            type: string
            nullable: true
            length: 15
            fixed: false
        latitud:
            type: decimal
            nullable: true
            precision: 10
            scale: 0
        longitud:
            type: decimal
            nullable: true
            precision: 10
            scale: 0
        idInstitucion:
            type: integer
            nullable: true
            unsigned: false
            column: id_institucion
        idMunicipio:
            type: integer
            nullable: true
            unsigned: false
            column: id_municipio
        anioApertura:
            type: integer
            nullable: true
            unsigned: false
            column: anio_apertura
        idCatNivelMinsal:
            type: integer
            nullable: true
            unsigned: false
            column: id_cat_nivel_minsal
        idEstablecimientoPadre:
            type: integer
            nullable: true
            unsigned: false
            column: id_establecimiento_padre
        registroSchema:
            type: datetime
            nullable: true
            column: registro_schema
        enableSchema:
            type: integer
            nullable: true
            unsigned: false
            column: enable_schema
    manyToMany:
        trnAsignacionid:
            targetEntity: TrnAsignacion
            cascade: {  }
            mappedBy: idCatEstablecimiento
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
