Minsal\CoreBundle\Entity\CatProducto:
    type: entity
    table: cat_producto
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codigoNu:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: codigo_nu
        grupoid:
            type: integer
            nullable: true
            unsigned: false
        codigoSinab:
            type: string
            nullable: false
            length: 10
            fixed: false
            column: codigo_sinab
        listadoOficial:
            type: boolean
            nullable: true
            column: listado_oficial
        nombreLargoInsumo:
            type: text
            nullable: true
            length: null
            fixed: false
            column: nombre_largo_insumo
        registroSchema:
            type: datetime
            nullable: true
            column: registro_schema
        enableSchema:
            type: integer
            nullable: true
            unsigned: false
            column: enable_schema
    manyToMany:
        trnAsignacionid:
            targetEntity: TrnAsignacion
            cascade: {  }
            mappedBy: catProductoid
            inversedBy: null
            joinTable: null
            orderBy: null
        idValeProvisional:
            targetEntity: ValeProvisional
            cascade: {  }
            mappedBy: catProductoid
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
