Minsal\CoreBundle\Entity\CatSuministro:
    type: entity
    table: cat_suministro
    indexes:
        IDX_8048948FF44034C1:
            columns:
                - cat_suministroid
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombreSuministro:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: nombre_suministro
        detalleSuministro:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: detalle_suministro
        registroSchema:
            type: datetime
            nullable: true
            column: registro_schema
        detalleSchema:
            type: text
            nullable: true
            length: null
            fixed: false
            column: detalle_schema
        userIdSchema:
            type: bigint
            nullable: true
            unsigned: false
            column: user_id_schema
        ipUserSchema:
            type: string
            nullable: true
            length: null
            fixed: false
            column: ip_user_schema
        estadoSchema:
            type: integer
            nullable: true
            unsigned: false
            column: estado_schema
        enableSchema:
            type: integer
            nullable: true
            unsigned: false
            column: enable_schema
        codificacionSuministro:
            type: bigint
            nullable: false
            unsigned: false
            column: codificacion_suministro
        rolSolicitaSuministro:
            type: bigint
            nullable: false
            unsigned: false
            column: rol_solicita_suministro
        rolValidaSuministro:
            type: bigint
            nullable: false
            unsigned: false
            column: rol_valida_suministro
    manyToOne:
        catSuministroid:
            targetEntity: CatSuministro
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cat_suministroid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
