Minsal\CoreBundle\Entity\CtlGrupo:
    type: entity
    table: ctl_grupo
    indexes:
        IDX_501FC6D876A39933:
            columns:
                - api_gruposuministroid
        IDX_501FC6D8F44034C1:
            columns:
                - cat_suministroid
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombreGrupo:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: nombre_grupo
        registroSchema:
            type: datetime
            nullable: true
            column: registro_schema
        enableSchema:
            type: integer
            nullable: true
            unsigned: false
            column: enable_schema
        codigoGrupo:
            type: bigint
            nullable: true
            unsigned: false
            column: codigo_grupo
    manyToOne:
        apiGruposuministroid:
            targetEntity: CtlGrupo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                api_gruposuministroid:
                    referencedColumnName: id
            orphanRemoval: false
        catSuministroid:
            targetEntity: CatSuministro
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cat_suministroid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
