Minsal\CoreBundle\Entity\TrnDistribucion:
    type: entity
    table: trn_distribucion
    indexes:
        IDX_32D979D39F4F768F:
            columns:
                - cat_estadoid
        IDX_32D979D3140FD2A0:
            columns:
                - seg_usuarioid
        IDX_32D979D35F311932:
            columns:
                - api_suministroid
        IDX_32D979D376A39933:
            columns:
                - api_gruposuministroid
    uniqueConstraints:
        trn_distribucion_id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        apiAlmacenid:
            type: integer
            nullable: false
            unsigned: false
            column: api_almacenid
        apiProgramaid:
            type: integer
            nullable: true
            unsigned: false
            column: api_programaid
        descripcion:
            type: text
            nullable: false
            length: null
            fixed: false
        fechadistribucion:
            type: date
            nullable: false
            comment: 'esta fecha se captura desde el sistema'
        fechacorte:
            type: date
            nullable: true
        mesesCpm:
            type: smallint
            nullable: true
            unsigned: false
            column: meses_cpm
        mesesDistribucion:
            type: smallint
            nullable: true
            unsigned: false
            column: meses_distribucion
        mesesAdministracion:
            type: smallint
            nullable: true
            unsigned: false
            column: meses_administracion
        mesesSeguridad:
            type: smallint
            nullable: true
            unsigned: false
            column: meses_seguridad
        fechaCreacion:
            type: date
            nullable: false
            column: fecha_creacion
        fechaModificacion:
            type: date
            nullable: true
            column: fecha_modificacion
    manyToOne:
        catEstadoid:
            targetEntity: CatEstados
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cat_estadoid:
                    referencedColumnName: id
            orphanRemoval: false
        segUsuarioid:
            targetEntity: SegUsuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                seg_usuarioid:
                    referencedColumnName: id
            orphanRemoval: false
        apiSuministroid:
            targetEntity: CtlSuministro
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                api_suministroid:
                    referencedColumnName: id
            orphanRemoval: false
        apiGruposuministroid:
            targetEntity: CtlGrupo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                api_gruposuministroid:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        ctlInsumo:
            targetEntity: CtlInsumo
            cascade: {  }
            mappedBy: null
            inversedBy: trnDistribucion
            joinTable:
                name: distribucion_producto
                joinColumns:
                    -
                        name: trn_distribucion_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: ctl_insumo_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
