Minsal\CoreBundle\Entity\TrnDetalle:
    type: entity
    table: trn_detalle
    indexes:
        IDX_D232DD2AD77BFB9A:
            columns:
                - id_trn_validacion
        IDX_D232DD2A297B5DA3BC0DA83B:
            columns:
                - id_trn_asignacion
                - cat_productoid
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        cpm:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
        cantidadDistribuir:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
            column: cantidad_distribuir
        cantidadSugerida:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
            column: cantidad_sugerida
        existenciaAlmacenes:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
            column: existencia_almacenes
        existenciaFarmacia:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
            column: existencia_farmacia
        apiEstablecimientoid:
            type: integer
            nullable: false
            unsigned: false
            column: api_establecimientoid
        verificar:
            type: boolean
            nullable: true
        fechaCreacion:
            type: date
            nullable: false
            column: fecha_creacion
        fechaModificacion:
            type: date
            nullable: true
            column: fecha_modificacion
    manyToOne:
        idTrnValidacion:
            targetEntity: TrnValidacion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_trn_validacion:
                    referencedColumnName: id
            orphanRemoval: false
        idTrnAsignacion:
            targetEntity: DistribucionProducto
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_trn_asignacion:
                    referencedColumnName: trn_asignacionid
                cat_productoid:
                    referencedColumnName: cat_productoid
            orphanRemoval: false
    manyToMany:
        idTrnEntregas:
            targetEntity: TrnEntregas
            cascade: {  }
            mappedBy: null
            inversedBy: idTrnDetalle
            joinTable:
                name: trn_detalles_entregas
                joinColumns:
                    -
                        name: id_trn_detalle
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: id_trn_entregas
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
