Minsal\CoreBundle\Entity\TrnDetalle:
    type: entity
    table: trn_detalle
    indexes:
        IDX_D232DD2A3CF50ACD:
            columns:
                - trn_distribucionid
        IDX_D232DD2A93154E863CF50ACD:
            columns:
                - api_establecimientoid
                - trn_distribucionid
        IDX_D232DD2AA645FFDB3CF50ACD:
            columns:
                - api_productoid
                - trn_distribucionid
    uniqueConstraints:
        trn_detalle_id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        cpm:
            type: decimal
            nullable: false
            precision: 15
            scale: 2
        cantidadDistribuir:
            type: decimal
            nullable: false
            precision: 15
            scale: 2
            column: cantidad_distribuir
        cantidadSugerida:
            type: decimal
            nullable: false
            precision: 15
            scale: 2
            column: cantidad_sugerida
        existenciaAlmacenes:
            type: decimal
            nullable: false
            precision: 15
            scale: 2
            column: existencia_almacenes
        existenciaFarmacia:
            type: decimal
            nullable: false
            precision: 15
            scale: 2
            column: existencia_farmacia
        verificar:
            type: boolean
            nullable: true
        observacion:
            type: text
            nullable: true
            length: null
            fixed: false
        fechaCreacion:
            type: date
            nullable: false
            column: fecha_creacion
        fechaModificacion:
            type: date
            nullable: true
            column: fecha_modificacion
    manyToOne:
        trnDistribucionid:
            targetEntity: TrnDistribucion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                trn_distribucionid:
                    referencedColumnName: id
            orphanRemoval: false
        apiEstablecimientoid:
            targetEntity: TrnEstablecimientosdistribucion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                api_establecimientoid:
                    referencedColumnName: api_establecimientoid
                trn_distribucionid:
                    referencedColumnName: trn_distribucionid
            orphanRemoval: false
        apiProductoid:
            targetEntity: TrnProductos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                api_productoid:
                    referencedColumnName: api_productoid
                trn_distribucionid:
                    referencedColumnName: trn_distribucionid
            orphanRemoval: false
    lifecycleCallbacks: {  }
