Minsal\CoreBundle\Entity\TrnEntregas:
    type: entity
    table: trn_entregas
    indexes:
        IDX_3CBBE85978372CFD:
            columns:
                - id_vale_provisional
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        cantidadDistribuida:
            type: decimal
            nullable: true
            precision: 10
            scale: 0
            column: cantidad_distribuida
        trnDetalleid:
            type: integer
            nullable: false
            unsigned: false
            column: trn_detalleid
        fechaDocumeento:
            type: date
            nullable: true
            column: fecha_documeento
        fechaCreacion:
            type: date
            nullable: false
            column: fecha_creacion
        fechaModificacion:
            type: date
            nullable: true
            column: fecha_modificacion
    manyToOne:
        idValeProvisional:
            targetEntity: ValeProvisional
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_vale_provisional:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        idTrnDetalle:
            targetEntity: TrnDetalle
            cascade: {  }
            mappedBy: idTrnEntregas
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
