Minsal\CoreBundle\Entity\TrnEstablecimientosdistribucion:
    type: entity
    table: trn_establecimientosdistribucion
    indexes:
        IDX_B143CDBF3CF50ACD:
            columns:
                - trn_distribucionid
    id:
        apiEstablecimientoid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: api_establecimientoid
    oneToOne:
        trnDistribucionid:
            targetEntity: TrnDistribucion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                trn_distribucionid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
