Minsal\CoreBundle\Entity\TrnProductos:
    type: entity
    table: trn_productos
    indexes:
        IDX_6788AB483CF50ACD:
            columns:
                - trn_distribucionid
    uniqueConstraints:
        trn_productos_api_productoid:
            columns:
                - api_productoid
    id:
        apiProductoid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: api_productoid
    fields:
        fechaModificacion:
            type: date
            nullable: false
            column: fecha_modificacion
        fechaCreacion:
            type: date
            nullable: true
            column: fecha_creacion
    oneToOne:
        trnDistribucionid:
            targetEntity: TrnDistribucion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                trn_distribucionid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
