Minsal\CoreBundle\Entity\TrnProductoslote:
    type: entity
    table: trn_productoslote
    indexes:
        IDX_CEB51674BC0DA83B:
            columns:
                - cat_productoid
    id:
        apiLoteid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: api_loteid
            generator:
                strategy: SEQUENCE
    fields:
        existencia:
            type: integer
            nullable: true
            unsigned: false
    manyToOne:
        catProductoid:
            targetEntity: CatProducto
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cat_productoid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
