Minsal\CoreBundle\Entity\TrnValidacion:
    type: entity
    table: trn_validacion
    indexes:
        IDX_EA1D469C140FD2A0:
            columns:
                - seg_usuarioid
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        estadoVerificado:
            type: boolean
            nullable: true
            column: estado_verificado
        fechaModificacion:
            type: date
            nullable: true
            column: fecha_modificacion
        cantidadPrelimimar:
            type: integer
            nullable: true
            unsigned: false
            column: cantidad_prelimimar
    manyToOne:
        segUsuarioid:
            targetEntity: SegUsuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                seg_usuarioid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
