establecimientos_index:
    path:     /
    defaults: { _controller: "MinsalCoreBundle:CatEstablecimiento:index" }
    methods:  GET

establecimientos_show:
    path:     /{id}/show
    defaults: { _controller: "MinsalCoreBundle:CatEstablecimiento:show" }
    methods:  GET

establecimientos_new:
    path:     /new
    defaults: { _controller: "MinsalCoreBundle:CatEstablecimiento:new" }
    methods:  [GET, POST]

establecimientos_edit:
    path:     /{id}/edit
    defaults: { _controller: "MinsalCoreBundle:CatEstablecimiento:edit" }
    methods:  [GET, POST]

establecimientos_delete:
    path:     /{id}/delete
    defaults: { _controller: "MinsalCoreBundle:CatEstablecimiento:delete" }
    methods:  DELETE

establecimientos_productos:
  path:       /{id}/productos
  defaults:   { _controller: "MinsalCoreBundle:CatEstablecimiento:getProductos"}
  methods:    GET
