asingaciones_index:
    path:     /
    defaults: { _controller: "MinsalCoreBundle:TrnAsignacion:index" }
    methods:  GET

asingaciones_show:
    path:     /{id}/show
    defaults: { _controller: "MinsalCoreBundle:TrnAsignacion:show" }
    methods:  GET

asingaciones_new:
    path:     /new
    defaults: { _controller: "MinsalCoreBundle:TrnAsignacion:new" }
    methods:  [GET, POST]

asingaciones_edit:
    path:     /{id}/edit
    defaults: { _controller: "MinsalCoreBundle:TrnAsignacion:edit" }
    methods:  [GET, POST]

asingaciones_delete:
    path:     /{id}/delete
    defaults: { _controller: "MinsalCoreBundle:TrnAsignacion:delete" }
    methods:  DELETE
