detalles_index:
    path:     /
    defaults: { _controller: "MinsalCoreBundle:TrnDetalle:index" }
    methods:  GET

detalles_show:
    path:     /{id}/show
    defaults: { _controller: "MinsalCoreBundle:TrnDetalle:show" }
    methods:  GET

detalles_new:
    path:     /new
    defaults: { _controller: "MinsalCoreBundle:TrnDetalle:new" }
    methods:  [GET, POST]

detalles_edit:
    path:     /{id}/edit
    defaults: { _controller: "MinsalCoreBundle:TrnDetalle:edit" }
    methods:  [GET, POST]

detalles_delete:
    path:     /{id}/delete
    defaults: { _controller: "MinsalCoreBundle:TrnDetalle:delete" }
    methods:  DELETE

detalles_otronombre:
    path:     /{id}/validacion
    defaults: { _controller: "MinsalCoreBundle:TrnValidacion:new" }
    methods:  [GET, POST]
